# docker-compose.yaml
version: "3.9"

services:
  fastapi:
    build:
      context: ./app
    image: fastapi-app:latest
    ports:
      - target: 80
        published: 8080
      - target: 12345
        published: 12345
    volumes:
      - type: bind
        source: ./app
        target: /app
    environment:
      - PYTHONPATH=/app:.:..
    command: uvicorn app.main:app --host 0.0.0.0 --port 80 --reload
